M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 16 14:38:00 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:38:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.85Y-3.45
X5.85Y-3.6
X5.9Y-3.8
X6.2856Y-3.6644
X6.3368Y-4.1632
X6.35Y-3.55
T2
X6.0Y-3.2
X6.2Y-3.2
T0
M30
